In [3]:
import pandas as pd
df = pd.Series([1,2,3,4])

In [11]:
Table=pd.read_excel('A_17.xlsx')

In [12]:
Table

        T        h         Pr        u        vr        s
0     200   199.97     0.3363   142.56  1707.000  1.29559
1     210   209.97     0.3987   149.69  1512.000  1.34444
2     220   219.97     0.4690   156.82  1346.000  1.39105
3     230   230.02     0.5477   164.00  1205.000  1.43557
4     240   240.02     0.6355   171.13  1084.000  1.47824
..    ...      ...        ...      ...       ...      ...
116  2050  2314.60  2303.0000  1726.80     2.555  3.83030
117  2100  2377.70  2559.0000  1775.30     2.356  3.86050
118  2150  2440.30  2837.0000  1823.80     2.175  3.89010
119  2200  2503.20  3138.0000  1872.40     2.012  3.91910
120  2250  2566.40  3464.0000  1921.30     1.864  3.94740

[121 rows x 6 columns]

In [41]:
x = 1.29559
def check_value_in_series(series, value):
    return value in series.values

check_value_in_series(Table['s'],x)

1.29559 in Table['s'].values

True

In [36]:
import pandas as pd

def check_value_in_series(series, value):
    return value in series.values

# 시리즈 생성
s = pd.Series([1, 2, 3, 4, 5])

# 값을 확인하고 싶은 값
target_value = 3

# 값이 시리즈 안에 있는지 확인
result = check_value_in_series(s, target_value)

# 결과 출력
print(result)

True

In [61]:
str(type(Table['s'])) == "<class 'pandas.core.series.Series'>"

True

In [63]:
str(type(s))=="<class 'pandas.core.series.Series'>"

True

In [65]:
str(type(12.33))=="<class 'pandas.core.series.Series'>"

False

In [66]:
type(-0.036)

float

In [102]:
table=pd.read_excel('A_11.xlsx')

In [103]:
table

,T,Psat,vf,vg,uf,ufg,ug,hf,hfg,hg,sf,sfg,sg
0,-40,51.25,0.000705,0.360640,−0.036,207.42,207.38,0.000,225.86,225.86,0.00000,0.96869,0.96869
1,-38,56.86,0.000708,0.327180,2.472,206.06,208.53,2.512,224.62,227.13,0.01071,0.95516,0.96588
2,-36,62.95,0.000711,0.297400,4.987,204.69,209.68,5.032,223.37,228.40,0.02137,0.94182,0.96319
3,-34,69.56,0.000714,0.270820,7.509,203.32,210.83,7.559,222.10,229.66,0.03196,0.92867,0.96063
4,-32,76.71,0.000717,0.247060,10.04,201.94,211.97,10.090,220.83,230.93,0.04249,0.91569,0.95819
5,-30,84.43,0.000720,0.225770,12.58,200.55,213.12,12.640,219.55,232.19,0.05297,0.90289,0.95586
6,-28,92.76,0.000723,0.206660,15.12,199.15,214.27,15.190,218.25,233.44,0.06339,0.89024,0.95364
7,-26,101.73,0.000726,0.189470,17.67,197.75,215.42,17.750,216.95,234.70,0.07376,0.87776,0.95152
8,-24,111.37,0.000730,0.173980,20.23,196.34,216.57,20.310,215.63,235.94,0.08408,0.86542,0.94950
9,-22,121.72,0.000733,0.159990,22.8,194.92,217.71,22.890,214.30,237.19,0.09435,0.85323,0.94758
10,-20,132.82,0.000736,0.147350,25.37,193.49,218.86,25.470,212.96,238.43,0.10456,0.84119,0.94575
11,-18,144.69,0.000739,0.135890,27.96,192.05,220.00,28.070,211.60,239.67,0.11473,0.82927,0.94401
12,-16,157.38,0.000743,0.125500,30.55,190.60,221.15,30.670,210.23,240.90,0.12486,0.81749,0.94234
13,-14,170.93,0.000746,0.116050,33.15,189.14,222.29,33.280,208.84,242.12,0.13493,0.80583,0.94076
14,-12,185.37,0.000750,0.107440,35.76,187.66,223.42,35.900,207.44,243.34,0.14497,0.79429,0.93925
15,-10,200.74,0.000753,0.099600,38.38,186.18,224.56,38.530,206.02,244.55,0.15496,0.78286,0.93782
16,-8,217.08,0.000757,0.092438,41.01,184.69,225.69,41.170,204.59,245.76,0.16491,0.77154,0.93645
17,-6,234.44,0.000761,0.085888,43.64,183.18,226.82,43.820,203.14,246.95,0.17482,0.76033,0.93514
18,-4,252.85,0.000764,0.079889,46.29,181.66,227.94,46.480,201.66,248.14,0.18469,0.74921,0.93390
19,-2,272.36,0.000768,0.074388,48.94,180.12,229.07,49.150,200.17,249.33,0.19452,0.73819,0.93271
20,0,293.01,0.000772,0.069335,51.61,178.58,230.18,51.830,198.67,250.50,0.20432,0.72726,0.93158
21,2,314.84,0.000776,0.064690,54.28,177.01,231.30,54.530,197.14,251.66,0.21408,0.71641,0.93050
22,4,337.90,0.000780,0.060412,56.97,175.44,232.40,57.230,195.58,252.82,0.22381,0.70565,0.92946
23,6,362.23,0.000784,0.056469,59.66,173.84,233.51,59.950,194.01,253.96,0.23351,0.69496,0.92847
24,8,387.88,0.000789,0.052829,62.37,172.23,234.60,62.680,192.42,255.09,0.24318,0.68435,0.92752
25,10,414.89,0.000793,0.049466,65.09,170.61,235.69,65.420,190.80,256.22,0.25282,0.67380,0.92661
26,12,443.31,0.000797,0.046354,67.82,168.96,236.78,68.170,189.16,257.33,0.26243,0.66331,0.92574
27,14,473.19,0.000802,0.043471,70.56,167.30,237.86,70.940,187.49,258.43,0.27201,0.65289,0.92490
28,16,504.58,0.000806,0.040798,73.31,165.62,238.93,73.720,185.80,259.51,0.28157,0.64252,0.92409
29,18,537.52,0.000811,0.038317,76.07,163.92,239.99,76.510,184.08,260.59,0.29111,0.63219,0.92330
30,20,572.07,0.000816,0.036012,78.85,162.19,241.04,79.320,182.33,261.64,0.30062,0.62192,0.92254
31,22,608.27,0.000821,0.033867,81.64,160.45,242.09,82.140,180.55,262.69,0.31012,0.61168,0.92180
32,24,646.18,0.000826,0.031869,84.44,158.68,243.13,84.980,178.74,263.72,0.31959,0.60148,0.92107
33,26,685.84,0.000831,0.030008,87.26,156.89,244.15,87.830,176.90,264.73,0.32905,0.59131,0.92036
34,28,727.31,0.000837,0.028271,90.09,155.08,245.17,90.700,175.03,265.73,0.33849,0.58117,0.91967
35,30,770.64,0.000842,0.026648,92.93,153.24,246.17,93.580,173.13,266.71,0.34792,0.57105,0.91897
36,32,815.89,0.000848,0.025131,95.79,151.37,247.17,96.490,171.19,267.67,0.35734,0.56095,0.91829
37,34,863.11,0.000853,0.023712,98.67,149.48,248.15,99.410,169.21,268.61,0.36675,0.55086,0.91760
38,36,912.35,0.000860,0.022383,101.56,147.55,249.11,102.340,167.19,269.53,0.37615,0.54077,0.91692
39,38,963.68,0.000866,0.021137,104.47,145.60,250.07,105.300,165.13,270.44,0.38554,0.53068,0.91622
40,40,1017.10,0.000872,0.019968,107.39,143.61,251.00,108.280,163.03,271.31,0.39493,0.52059,0.91552
41,42,1072.80,0.000879,0.018870,110.34,141.59,251.92,111.280,160.89,272.17,0.40432,0.51048,0.91480
42,44,1130.70,0.000885,0.017837,113.3,139.53,252.83,114.300,158.70,273.00,0.41371,0.50036,0.91407
43,46,1191.00,0.000892,0.016866,116.28,137.43,253.71,117.340,156.46,273.80,0.42311,0.49020,0.91331
44,48,1253.60,0.000900,0.015951,119.28,135.30,254.58,120.410,154.17,274.57,0.43251,0.48001,0.91252
45,52,1386.20,0.000915,0.014276,125.35,130.89,256.24,126.620,149.41,276.03,0.45136,0.45948,0.91084
46,56,1529.10,0.000932,0.012782,131.52,126.29,257.81,132.940,144.41,277.35,0.47028,0.43870,0.90898
47,60,1682.80,0.000950,0.011434,137.79,121.45,259.23,139.380,139.09,278.47,0.48930,0.41746,0.90676
48,65,1891.00,0.000975,0.009959,145.8,115.06,260.86,147.640,132.05,279.69,0.51330,0.39048,0.90379
49,70,2118.20,0.001004,0.008650,154.03,108.17,262.20,156.150,124.37,280.52,0.53763,0.36239,0.90002
50,75,2365.80,0.001037,0.007486,162.55,100.62,263.17,165.010,115.87,280.88,0.56252,0.33279,0.89531
51,80,2635.30,0.001077,0.006439,171.43,92.22,263.66,174.270,106.35,280.63,0.58812,0.30113,0.88925
52,85,2928.20,0.001127,0.005484,180.81,82.64,263.45,184.110,95.39,279.51,0.61487,0.26632,0.88120
53,90,3246.90,0.001194,0.004591,190.94,71.19,262.13,194.820,82.22,277.04,0.64354,0.22638,0.86991
54,95,3594.10,0.001295,0.003713,202.49,56.25,258.73,207.140,64.94,272.08,0.67605,0.17638,0.85243
55,100,3975.10,0.001527,0.002657,218.73,29.72,248.46,224.800,34.22,259.02,0.72224,0.09169,0.81393

In [104]:
-2 in table['T'].values

True

In [82]:
float(-40) in table['T'].values

False

In [83]:
any(table['T'] == -2)

False

In [87]:
import pandas as pd

# 시리즈 생성
s = pd.Series([-1, -2, -3])

# 값을 확인하고 싶은 값
target_value = -2

a=table['T']

# 값이 시리즈 안에 있는지 확인
result = target_value in a.values

# 결과 출력
print(result)

False

In [86]:
import pandas as pd

# 데이터프레임 생성
data = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [-2, 8, 9]}
df = pd.DataFrame(data)

# 특정 열 가져오기
series = df['col3']

# 값을 확인하고 싶은 값
target_value = -2

# 값이 시리즈 안에 있는지 확인
result = target_value in series.values

# 결과 출력
print(result)

True

In [88]:
df

   col1  col2  col3
0     1     4    -2
1     2     5     8
2     3     6     9

In [91]:
-2 in series.values

True

In [99]:
table['T'].dtype

dtype('O')

In [100]:
table['sfg'].dtype

dtype('float64')

In [101]:
a=table['T'].astype(float)

ValueError: could not convert string to float: '−40'